// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAEuHIjGrNZzcDmrI9PpWSqC5_aNu6lx0',
    appId: '1:100999325622:web:bcd04f91f80a1e697b0317',
    messagingSenderId: '100999325622',
    projectId: 'e-book-store-7e217',
    authDomain: 'e-book-store-7e217.firebaseapp.com',
    storageBucket: 'e-book-store-7e217.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwxV4wdbDl82InrneQ0Vt9tDCrk8laSks',
    appId: '1:100999325622:android:be4ea153c7c5d0257b0317',
    messagingSenderId: '100999325622',
    projectId: 'e-book-store-7e217',
    storageBucket: 'e-book-store-7e217.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxV_i0qLRXl1l-w6P2OeqMePquaLCyoK0',
    appId: '1:100999325622:ios:2e422fecc137e5017b0317',
    messagingSenderId: '100999325622',
    projectId: 'e-book-store-7e217',
    storageBucket: 'e-book-store-7e217.firebasestorage.app',
    iosBundleId: 'com.example.flutterEbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxV_i0qLRXl1l-w6P2OeqMePquaLCyoK0',
    appId: '1:100999325622:ios:2e422fecc137e5017b0317',
    messagingSenderId: '100999325622',
    projectId: 'e-book-store-7e217',
    storageBucket: 'e-book-store-7e217.firebasestorage.app',
    iosBundleId: 'com.example.flutterEbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAEuHIjGrNZzcDmrI9PpWSqC5_aNu6lx0',
    appId: '1:100999325622:web:2cb6d1786ccab2287b0317',
    messagingSenderId: '100999325622',
    projectId: 'e-book-store-7e217',
    authDomain: 'e-book-store-7e217.firebaseapp.com',
    storageBucket: 'e-book-store-7e217.firebasestorage.app',
  );
}
